language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
install:
  - pip3 install -r requirements.txt
  - python3 bin/bootstrap-buildout.py
  - bin/buildout
script:
  - bin/py.test --cov=grader -v redkyn-grader/
